// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzvmghrajbmptzwwzqwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6dm1naHJhamJtcHR6d3d6cXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1ODgwODksImV4cCI6MjA2MDE2NDA4OX0.3vNJbhXqCh1yoYXMh62o6ktLun_SLHi9jDAalEvrFz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);